from __future__ import annotations

import io
import logging
import time
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
from PIL import Image
from transformers import AutoProcessor

from app.config import RuntimeConfig
from app.parser import clamp_bbox, parse_bbox

LOGGER = logging.getLogger(__name__)

SYSTEM_PROMPT = "Return only the bounding box as [x0,y0,x1,y1] in pixels. No other text."


@dataclass
class RequestTiming:
    preprocess_ms: float
    infer_ms: float
    postprocess_ms: float


class Qwen2VLBBoxEngine:
    def __init__(self, cfg: RuntimeConfig) -> None:
        self.cfg = cfg
        if cfg.batch_size != 1:
            raise ValueError("batch_size must remain 1 for latency optimization")

        self.processor = AutoProcessor.from_pretrained(cfg.model_dir, local_files_only=True)
        self._hailo_runner = self._build_hailo_runner(cfg)
        self._decoder = self._build_decoder(cfg)

    def _build_hailo_runner(self, cfg: RuntimeConfig):
        """
        Runtime hook:
        - Run Qwen2-VL vision encoder subgraph on Hailo 10H via HailoRT 5.2.0.
        - Use HEF generated by hailo_gen_ai_model_zoo 5.2.0.
        """
        from hailo_platform import HEF, VDevice  # type: ignore

        hef = HEF(cfg.hailo_hef_path)
        device = VDevice()
        infer_model = device.create_infer_model(hef)
        configure_params = infer_model.create_configure_params()
        configured = infer_model.configure(configure_params)
        return configured

    def _build_decoder(self, cfg: RuntimeConfig):
        """
        CPU-side decoder/token generation path for Qwen2-VL-2B-Instruct language head.
        """
        from transformers import Qwen2VLForConditionalGeneration

        model = Qwen2VLForConditionalGeneration.from_pretrained(
            cfg.model_dir,
            local_files_only=True,
            torch_dtype="auto",
            device_map="cpu",
        )
        model.eval()
        return model

    def _prepare_image(self, image_bytes: bytes) -> Tuple[Image.Image, Tuple[int, int]]:
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        width, height = image.size
        if max(width, height) > self.cfg.max_image_dim:
            image.thumbnail((self.cfg.max_image_dim, self.cfg.max_image_dim), Image.Resampling.BILINEAR)
        if self.cfg.jpeg_quality < 95:
            buf = io.BytesIO()
            image.save(buf, format="JPEG", quality=self.cfg.jpeg_quality, optimize=False)
            image = Image.open(io.BytesIO(buf.getvalue())).convert("RGB")
        return image, (width, height)

    def _run_hailo_vision_encoder(self, image_tensor: np.ndarray) -> np.ndarray:
        bindings = self._hailo_runner.create_bindings()
        input_name = next(iter(bindings.input().keys()))
        output_name = next(iter(bindings.output().keys()))
        bindings.input()[input_name].set_buffer(image_tensor)
        self._hailo_runner.run(bindings)
        return bindings.output()[output_name].get_buffer()

    def _decode_bbox(self, image: Image.Image, query: str, encoded_vision: np.ndarray) -> str:
        prompt = (
            f"<|im_start|>system\n{SYSTEM_PROMPT}<|im_end|>\n"
            f"<|im_start|>user\nLocate: {query}<|im_end|>\n<|im_start|>assistant\n"
        )
        model_inputs = self.processor(text=[prompt], images=[image], return_tensors="pt")
        if "vision_embeds" in model_inputs:
            model_inputs["vision_embeds"] = encoded_vision

        generated = self._decoder.generate(
            **model_inputs,
            max_new_tokens=self.cfg.max_new_tokens,
            temperature=self.cfg.temperature,
            top_p=self.cfg.top_p,
            repetition_penalty=self.cfg.repetition_penalty,
            do_sample=False,
            eos_token_id=self.processor.tokenizer.eos_token_id,
        )
        text = self.processor.batch_decode(generated, skip_special_tokens=True)[0]
        end_idx = text.find(self.cfg.stop_sequence)
        return text if end_idx < 0 else text[: end_idx + 1]

    def infer(self, image_bytes: bytes, query: str) -> Tuple[List[int], RequestTiming]:
        t0 = time.monotonic_ns()
        image, original_size = self._prepare_image(image_bytes)
        image_tensor = np.asarray(image, dtype=np.uint8)
        t1 = time.monotonic_ns()

        encoded_vision = self._run_hailo_vision_encoder(image_tensor)
        raw_output = self._decode_bbox(image, query, encoded_vision)
        t2 = time.monotonic_ns()

        bbox = clamp_bbox(parse_bbox(raw_output), *original_size)
        t3 = time.monotonic_ns()

        timing = RequestTiming(
            preprocess_ms=(t1 - t0) / 1_000_000,
            infer_ms=(t2 - t1) / 1_000_000,
            postprocess_ms=(t3 - t2) / 1_000_000,
        )
        return bbox, timing

    def warmup(self) -> None:
        LOGGER.info("Warming Qwen2-VL pipeline")
        dummy = Image.new("RGB", (256, 256), color=(127, 127, 127))
        b = io.BytesIO()
        dummy.save(b, format="JPEG", quality=80)
        self.infer(b.getvalue(), self.cfg.warmup_query)
